(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var d,e="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function f(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var h=f(this),k;
if("function"==typeof Object.setPrototypeOf)k=Object.setPrototypeOf;else{var l;a:{var m={a:!0},n={};try{n.__proto__=m;l=n.a;break a}catch(a){}l=!1}k=l?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var p=k;
function q(a,b){a.prototype=e(b.prototype);a.prototype.constructor=a;if(p)p(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var g=Object.getOwnPropertyDescriptor(b,c);g&&Object.defineProperty(a,c,g)}else a[c]=b[c];a.l=b.prototype};function r(a){return a.hasAttribute("direction")?a.getAttribute("direction"):"lefttoright"};function t(){var a=HTMLElement.call(this)||this;a.i=null;a.h=0;a.g=0;return a}q(t,HTMLElement);d=t.prototype;d.connectedCallback=function(){this.j||(this.j=window.setTimeout(this.gwdLoad.bind(this),0))};
d.gwdLoad=function(){this.j&&(clearTimeout(this.j),this.j=void 0);var a=this.parentElement.querySelector("canvas");a&&(this.i=a.getContext("2d"),this.h=parseInt(a.style.width,10),this.g=parseInt(a.style.height,10));var b=void 0===b?null:b;a=document.createEvent("CustomEvent");a.initCustomEvent("ready",!0,!0,b);this.dispatchEvent(a)};d.gwdIsLoaded=function(){return!!this.i};d.renderAnimation=function(){};function u(a,b,c,g){a.i.drawImage(b,c,g,a.h,a.g)}
d.getSupportedSwipeDirection=function(){if("undefined"===typeof this.direction)return[0,0];switch(this.direction){case "lefttoright":return[1,0];case "righttoleft":return[-1,0];case "toptobottom":return[0,1];case "bottomtotop":return[0,-1];default:return[0,0]}};d.setDirection=function(){};d.resetDirection=function(){};var v=["direction"];function w(){return t.apply(this,arguments)||this}q(w,t);d=w.prototype;d.connectedCallback=function(){this.direction=r(this);t.prototype.connectedCallback.call(this)};d.attributeChangedCallback=function(a){switch(a){case "direction":this.direction=r(this)}};d.setDirection=function(a){this.direction=a};d.resetDirection=function(){this.direction=r(this)};
d.renderAnimation=function(a,b,c){this.i.save();this.i.clearRect(0,0,this.h,this.g);switch(this.direction){case "righttoleft":u(this,b,(1-c)*this.h,0);u(this,a,-c*this.h,0);break;case "toptobottom":u(this,b,0,(c-1)*this.g);u(this,a,0,c*this.g);break;case "bottomtotop":u(this,b,0,(1-c)*this.g);u(this,a,0,-c*this.g);break;default:u(this,b,(c-1)*this.h,0),u(this,a,c*this.h,0)}this.i.restore()};h.Object.defineProperties(w,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return v}}});
customElements.define("gwd-push",w);}).call(this);
